<a href="https://colab.research.google.com/github/ehdghks316/itwill_studyGroup_D/blob/main/3_3%ED%8C%8C%EC%9D%B4%EC%8D%AC%EA%B8%B0%EC%B4%882.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
king = [['주몽','유리왕','대무신왕'],['태종무열왕','경덕왕'],['은조왕','개로왕']]

#[문제 12] 1번 인덱스에 '원성왕' 추가하세요.
king[1].append('원성왕')

#[문제13] 2번 인덱스에 '무왕' 추가하세요.
king[2].append('무왕')

#[문제14] 0번 인덱스에 '대무신왕' 추가하세요.
king[0].append('대무신왕')

#[문제15] 0번 인덱스에 '미천왕','미천왕','광개토대왕' 추가하세요.
king[0].extend(['미천왕','미천왕','광개토대왕']) #king[0] = king[0]+['미천왕','미천왕','광개토대왕']
king
#[문제16] 2번 인덱스 2번 위치에 성왕 추가하세요.
king[2].insert(2,'성왕')
king

#[문제17] '미천왕' 건수를 세어주세요.
king[0].count('미천왕')

#[문제18] 0번 인덱스만 오름차순 정렬
king[0].sort()
king

#[문제19] 1번 인덱스만 내림차순 정렬
king[1].sort(reverse = True)

#[문제20] 0번 인덱스에 마지막 데이터를 삭제해주세요.
king[0].pop()
king

In [ ]:
'''
2. tuple
- 리스트와 유사하지만 수정, 삭제, 추가를 할 수 없다.
- ()
'''

lst = []
type(lst)

tuple1 = ()
type(tuple1)

tuple2 = 10,20
type(tuple2)

tuple3 = (10,)
type(tuple3)

tuple4 = (1,2,3,4,5)
tuple4

tuple5 = ('a','b',('ab','bc'))
tuple5[2][0]

tuple6 = (1,2,('ab','bc'))
type(tuple6[0])
type(tuple6[2][0])

x = (1,2,3)
y = (4,5,6)
z = x + y # 여러 튜플을 하나로 결합하는 방법
type(z)

# z[0] = 10   튜플은 수정 불가능, 오류 발생
# del z[0]  튜플은 삭제도 불가능, 오류 발생
# z.remove(1) 오류
# z.pop() 오류
# z.append(7) 튜플 삽입 불가능, 오류

# z.sort()  정렬도 불가능, 오류
sorted(z) # 튜플변수에 있는 값을 정렬하려면 sorted를 수행해야한다.
sorted(z,reverse=True)

z[::-1] # 튜플변수에 값을 역순으로 수행
# z.reverse() 튜펼변수에 값을 역순으로 수행하는 reverse함수는 수행할 수 없다.

z.index(1)
z.count(1)

x = 1,2,3
type(x)
one,two,three = x
one
two
three

q,r = divmod(11,2)
q
r

lst = [1,2,3]
lst
x = lst[0]
y = lst[0:2]

x,y = lst[0:2]
x,y

del z # 튜플 변수 삭제
dir()
#id(z)

In [ ]:
'''
3. dictionary
- key, value 값을 가지는 자료형이다.
- {}
- {key1:value1,key2:value2,,,,,}
'''

dic = {}
type(dic)

dic = {'이름':'홍길동','전화번호':'010-1000-1004','주소':'서울'}
dic['이름']
dic['전화번호']
dic.keys() # key값들 추출
dic.values() # value값들 추출
dic.items() # key,value 같이 추출

sports = {'축구':'메시','농구':'하든','야구':'박찬호'}
sports['축구']
sports['컬링'] = '김영미' # key, value값 추가
sports['컬링'] = ['김영미','김은정','김경애','김선영','김초희'] # key값 하나에 여러 value값 가능
sports

sports['농구']
# sports.get['농구']

# sports['골프'] 키가 없으면 오류
sports.get('골프') # 키가 없으면 none으로 리턴

'농구' in sports.keys()
'골프' in sports.keys()
'메시' in sports.values()
['김영미','김은정','김경애','김선영','김초희'] in sports.values()

del sports['야구'] # key,value 삭제
sports

sports['축구'] = [] # value값만 삭제
sports

sports['축구'] = '손흥민'
sports

sports['축구'] = ''
sports

sports['축구'] = [] # value값 삭제
sports

v = sports.values()
type(v)
list(v)

list(sports.keys())
list(sports.items())

In [ ]:
'''
4. set
- 집합
- 리스트와 비슷하다. 단 인덱스가 없다.
- 중복을 허용하지 않는다.
- {}
'''
s = {1,1,1,1,2,2,2,2,3,3,3,4,5}
s
type(s)

lst = [1,1,1,1,2,2,2,2,3,3,3,4,5]
lst.count(1)
list(set(lst))
lst[0]

x = {1,2,3,6}
y = {1,2,3,4,5}

# 합집합
set(x).union(set(y)) # 리스트 변수의 값은 union 할 수 없다. 꼭 자료형을 set으로 수정해야한다.

x.union(y)
y.union(x)
x|y

# 교집합
x.intersection(y)
x&y

# 차집합
x.difference(y)
x-y

# 대칭차집합(symmetric difference)
(x-y)|(y-x)
(x-y).union(y-x)
x.symmetric_difference(y)

# 서로소 집합(disjoint set) : 두 집합에 공통된 원소가 없는 집합
{1,2,3}.isdisjoint({1,2,3})
{1,2,3}.isdisjoint({4,5,6})

# 부분집합(subset)
{1,2,3}.issubset({1,2,3,4})
{1,2,3}<={1,2,3,4}
{5,6,7}<={1,2,3,4}

x = {1,2,3}
y = {1,2,3,4}
x <= y
x.issubset(y)
y.issubset(x)
y.issuperset(x) # 상위집합인지 확인하는 함수

1 in x
7 in y

# x[0] # 집합은 인덱스를 사용할 수 없다.
x.remove(1) # 집합에 있는 값을 삭제
x.add(1) # 집합에 값을 추가
x.update([8,9]) # 집합에 여러개의 값을 추가
# 집합에 있는 값은 수정할 수 없기 때문에 지우고 다시 추가 하면된다.

l = []
type(l)
s = ()
type(s)
d = {}
type(d)

In [ ]:
'''
5. bool
- 참(True), 거짓(False)을 나타내는 자료형
'''

x = True
y = False
type(x)
type(y)

# 조건제어문에서 True 표현 방법
bool(1)
bool(100)
bool(-1)
bool('홍길동')
bool('python')
bool([1,2,3])
bool((1,2,3))
bool({1,2,3})

# 조건제어문에서 False 표현 방법
bool(0)
bool(None)
bool([])
bool({})
bool(())
bool('')
bool("")

not 1
not -1

In [212]:
# 파이썬 변수 복제 주의
x = [1,2,3]
y = x # x변수와 y변수는 동일한 메모리 공간을 사용한다.
y
x[0] = 10
x
y # x값이 바뀌면 똑같이 y값도 바뀐다
y[1] = 20
x # y값이 바뀌면 똑같이 x값도 바뀐다.
y
id(x)
id(y) #메모리값이 x와 동일한 것을 알 수 있다.

x = [1,2,3]
z = x[:] # x변수를 복제하지만 다른 메모리 공간을 사용한다.
id(x)
id(z)
x[0] = 10
x
z

import copy
x = [1,2,3]
w = copy.deepcopy(x) # x변수를 복제하지만 다른 메모리 공간을 사용한다.
w
id(x)
id(w)

x[0] = 100
x
w

[1, 2, 3]

In [ ]:
'''
input()
- 사용자로부터 입력을 받아들여 프로그램에 전달하는 함수
- 문자형으로 전달된다.
'''
x = input()
x
type(x)

y = input()
y
x + y # 문자열 조합

int(x) + int(y)

x = int(input())
x 
type(x)

y = int(input())
y

x + y # 문자열 조합

In [ ]:
# 조건제어문
'''
1. if문

if 조건문 :
  수행해야할 문장

if 조건문 :
  True일 때 수행해야할 문장
else :
  False일 때 수행해야할 문장
'''

x = 10
if x == 10:
  print("오늘 하루도 10배 행복하자")

x = 20
if x == 10:
  print("오늘 하루도 10배 행복하자")
else:
  print("오늘 하루도 {}배 행복하자.".format(x))

x = 20 
if x == 10:
  print("오늘 하루도 10배 행복하자")
else:
  print("오늘 하루도 %s배 행복하자"%(x))

if 1:
  print('참')
else:
  print('거짓')

if 0:
  print('참')
else:
  print('거짓')

if [1,2]:
  print('참')
else:
  print('거짓')

if []:
  print('참')
else:
  print('거짓')

if True:
  print('참')
else:
  print('거짓')

if False:
  print('참')
else:
  print('거짓')

x = 12
if x > 10 and x%2 ==0:
  print('참')
else:
  print('거짓')

x = 0 
if x> 10 and x%2 == 0:
  print('참')
else:
  print('거짓')

x = 4
if x> 10 or x%2 ==0:
  print('참')
else:
  print('거짓')

num = int(input("점수를 입력해주세요 :"))
num

if 90 <= num <= 100:
  grade = 'A'
elif 80 <= num < 90:
  grade = 'B'
elif 70 <= num < 80:
  grade = 'C'
elif 60 <= num < 70:
  grade = 'D'
else:
  grade = 'F'

grade
print('학점은 ' + grade)
print('학점은 {}'.format(grade))
print('학점은 %s'%(grade))

In [ ]:
#[문제21] 숫자를 입력값으로 받아서 그 값이 짝수면 짝수, 홀수면 홀수를 출력해세요.
x = int(input())
if x%2 ==0:
  print('짝수')
else:
  print('홀수')

#[문제22] 한글, alphabet만 입력받아서 문자를 출력하고 아니면 "다른 문자가 포함되어 있습니다"를 출력해주세요.
x = input()
if x.replace(" ","").isalpha() == True:
  print(x)
else:
  print('다른 문자가 포함되어 있습니다.')

#[문제23] 숫자를 입력값으로 받아서 숫자면 입력받은 숫자를 출력하고 아니면 "숫자 이외의 문자가 포함되어 있습니다" 출력해주세요.
x = input()
if x.isnumeric() == True:
  print(x)
else:
  if x == "":
    print('입력값이 없습니다.')
  else:
    print('숫자 이외의 문자가 포함되어 있습니다.')

In [ ]:
x == '' # 빈문자열 비교
x == ""
x == None # 빈문자열은 None으로 비교하면 False

x = None
x == ''
x == None # None은 None으로 비교

if x == None:
  print('참')
else:
  print('거짓')

if x is None:
  print('참')
else:
  print('거짓')

num = 1
type(num)

# num.isnumeric() # isnumeric() 함수는 문자 변수에서 숫자를 체크하는 함수

isinstance(num,int) # 변수의 타입을 체크해서 일치하면 True 아니면 False를 리턴하는 함수

num = '1'
isinstance(num,int)
isinstance(num,str)

f = 1,2
type(f)
isinstance(f,int)
isinstance(f,float)
isinstance(f,str)

b = True
isinstance(b,str)
isinstance(b,bool)

dir()
#del str

x = [1,2]
y = [2,1]

x == y # 안에 있는 인덱스의 위치와 값끼리 비교하는 것
x[0] == y[0] and x[1] == y[1]

set(x) == set(y) # 값으로 비교하고 싶을 때 집합(set)으로 바꿔서 해야한다.

sal = 1000
comm = None
# sal * comm

if comm is None:
  annual = sal * 12
else:
  annual = sal * 12 + comm

print(annual)

# 참값 if 조건 else 거짓
annual = sal * 12 if comm is None else sal * 12 + comm
annual

In [ ]:
# 반복문
'''
1. while 문
- 조건이 True인 동안에 반복을 수행한다.

while 조건문:
  반복수행할 문장
'''
i = 0
while i <= 10:
  print(i)
  i += 1 #i = i + 1

In [290]:
#[문제 24] 1부터 100까지 합을 구하세요.
i = 0
hap = 0
while i <= 100:
  hap += i
  i += 1
print(hap)

#[문제 25] 1부터 100까지 3의 배수를 출력하고 합도 구하세요
i = 0
hap = 0
while i <= 100:
  if i%3==0:
    hap += i
  i += 1
print(hap)

#[문제 26] 1부터 10까지 홀수값만 출력해주세요.
i = 0
x = 0
while i <= 10:
  if i%2 ==0:
    i += 1
    continue
  else:
    print(i)
    i += 1
  if i >= 10:
    break # 반복문 중단 함수

i = 0
while i < 10:
    i += 1
    if i%2 == 0:
        continue # continue문을 만나는 순간 바로 다음 반복을 수행한다.
    print(i)

i = 0
while True:
  if i == 0:
    i = 1
  elif i > 10:
    break
  print(i)
  i += 2

5050
1683
1
3
5
7
9
1
3
5
7
9
1
3
5
7
9