<a href="https://colab.research.google.com/github/ehdghks316/itwill_studyGroup_D/blob/main/3_14%ED%8C%8C%EC%9D%B4%EC%8D%AC(pandas_Series%2CDataFrame).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
★ pandas
- 데이터분석 기능을 제공하는 라이브러리
- 1차원배열 : Series
- 2차원배열 : DataFrame

from pandas import Series,DataFrame
import pandas as pd # 별칭으로 pd

Series 
- 1차원배열
- 인덱스(색인) 배열의 데이터에 연관된 이름을 가지고 있다.
- R의 벡터 자료형하고 비슷하다.
- 단일 데이터 타입만 가능하다.(숫자와 문자가 같이 있으면 문자)

lst = [1,2,3,4,5]
lst[0] + 100  # 개별인덱싱으로 연산을 수행해야했음
[i + 100 for i in lst]

s1 = Series([10,20,30,40,50])
s1 # int형
s1 + 100 # 개별인덱싱을 안해도 바로 연산이 가능
type(s1)
s1.astype

s1 = Series(['10',20,30,40,50])
s1 # object형 (문자형/character)
s1 + 100 # 오류
type(s1)
s1.astype('int32') # Series 데이터 타입을 수정(미리보기)
s1 = s1.astype('int64') # 자료형 수정
s1.index
s1.values
s1.index = ['a','b','c','d','e'] # 인덱스 수정
s1

s1 + 100
s1-100
s1 * 10
s1/2
s1//2
s1%2
s1**2

s1['a'] # 인덱스를 이용해서 값을 추출
s1[['a','c']]
s1[0] # 위치를 이용해서 값을 추출
s1[3]
s1[0:3]
s1[-1]

s1 >= 30
s1[s1 >= 30] 

'a' in s1
'f' in s1

s1['a'] = 100 # 값을 수정
s1['f'] = 500 # 새로운 값을 추가
s1['a'] = '' # 빈문자열 수정하면 int형에서 objecg형으로 변경됨
del s1['a'] # 요소를 삭제
s1
del s1 # 변수 삭제

lst = [10,20,30]
type(lst)
Series(lst)

t = (10,20,30)
type(t)
Series(t)

dict = {'a':10, 'b':20, 'c':30}
dict
Series(dict) # key가 인덱스가 됨

ix = {'a','b'}
type(ix)
Series(dict,index=ix)

ix = {'a','b','f'} #중복되는 인덱스가 발생하지 않도록 집합 자료형 사용
type(ix)
s1 = Series(dict,index=ix) # NaN(Not a Number) : 인덱스값을 찾을 수 없을 경우 NaN으로 저장
s1 

ix = ['a','b','a','f']
s1 = Series(dict,index=ix) # 중복되는 인덱스가 만들어진다. 주의!
s1

ix = ['a','b','f']
s1 = Series(dict,index=ix) 
s1

ix = ('a','b','f')
s1 = Series(dict,index=ix) 
s1

# NaN : SQL(NULL), R(NA) 같은 개념
import pandas as pd
pd.isnull(s1) # NaN값을 체크하는 방법
s1[pd.isnull(s1)]

pd.notnull(s1) # NaN이 아닌값을 체크
s1[pd.notnull(s1)]

s1['f'] = ''
s1

s1 = Series(dict,index=['a','b','f'])
s1
s1['f'] = ''
s1
pd.isnull(s1) # NaN 체크
s1 == '' # 빈문자열 체크

s1['f'] = None # null(NaN)로 수정
s1
pd.isnull(s1)

import numpy as np
s1['f'] = np.NaN # NaN 수정
s1
pd.isnull(s1)
s1.astype('int64') # NaN이 있으면 int형 불가
s1.astype('float32')
s1.astype('float64') # NaN이 있을 경우 float형으로 수정


d1 = {'서울':500,'부산':300,'경기':700, '제주':200}
s1 = Series(d1)
s1

city = {'서울','경기','제주','대전'}
s2 = Series(d1,index=city)
s2

# 서로 다른 Series에 인덱스를 기준으로 연산작업
s1 + s2

# 이 변수의 값들이 무엇을 뜻하는지 기록 name
s1.name = '인구수'
s1.name = ''
s1.name = None 
s1
s1.index.name = '지역명'
s1.index.name = None
s1

DataFrame
- 2차원배열(행과 열로 구성)
- 표 형식(테이블)의 자료구조
- 각 컬럼은 서로 다른 종류 데이터 타입을 사용할 수 있다.(문자,숫자,불리언)

df = DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df
type(df)

data = {'도시':['서울','부산','강원','인천'],
        '인구수':[500,400,200,300]}

df = DataFrame(data)
df.info() # 데이터프레임의 정보를 확인
df.columns # 컬럼 이름 정보
df.index # 인덱스 정보
df.values # 값 정보

df.columns = ['지역','가구수'] # 컬럼 수정
df

df.지역 # 열선택
type(df.지역)

df.가구수 * 100

df.index = ['one','two','three','four'] # 인덱스 수정
df

# 행선택
df.iloc[0] # 인덱스 위치를 사용
df.iloc[1]
df.iloc['one'] # iloc 인덱스 이름을 사용하면 오류 발생

df.loc['one'] # 인덱스 이름을 사용
df.loc[0] # 인덱스 위치를 사용하면 오류 발생

data = {'도시':['서울','부산','강원','인천'],
        '인구수':[500,400,200,300]}

df = DataFrame(data)

df.iloc[0] # 인덱스 위치
df.loc[0] # 인덱스 이름

df.도시 # 열선택
df['도시'] # 열선택

df['부채'] = [1000,300,100,50] # 열을 추가
df

del df['부채'] # 열 삭제
df

data = {'서울':{2001:200,2002:300},
        '부산':{2000:100,2001:50,2002:200}}

df = DataFrame(data)
df.index
df.values
df
df.T # 행과 열을 바꾸는 방법
df.dtypes # 각 컬럼별로 타입확인
df.서울.dtype 
df.info()


obj = Series([10,20,30,40],index = ['c','d','a','b'])
obj

# reindex : 새로운 색인에 맞도록 객체를 새로 생성하는 기능
obj1 = obj.reindex(['a','b','c','d'])
obj1

obj2 = obj.reindex(['a','b','c','d','e'])
obj2

obj3 = obj.reindex(['a','b','c'])
obj3

Series(obj,index=['a','b','c'])
Series(obj,index=('a','b','c'))
s = Series(obj,index={'a','b','c'}) # set자료형은 순서가 없음
s = s.reindex(['a','b','c'])
s

obj.reindex(['a','b','c','d','e'])
obj_new = obj.reindex(['a','b','c','d','e'], fill_value=0) # 없는 값은 0으로 채우겠다
obj_new

list(range(4))
np.arange(4).reshape(2,2) # 2행2열로 1~4까지의 값을 넣음
np.arange(9).reshape(3,3)
np.arange(12).reshape(3,4)

df = DataFrame(np.arange(9).reshape(3,3),
          index=['a','b','c'],
          columns=['x','y','z'])
df
df.reindex(['b','c','a'])

df1 = df.reindex(['a','b','c','d'])
df1

df1 = df.reindex(['a','b','c','d'],fill_value=0) # reindex 할 때 새로운 인덱스는 NaN값 대신 0으로 채워진다.
df1

# method = 'ffill','pad' NaN값을 앞의 행의 값으로 채운다
df1 = df.reindex(['a','b','c','d'],method='ffill')
df1
df1 = df.reindex(['a','b','c','d'],method='pad')
df1

df = DataFrame(np.arange(9).reshape(3,3),
          index=['a','c','d'],
          columns=['x','y','z'])
df

df.reindex(['a','b','c','d'])

# method = 'bfill', 'backfill' NaN값을 뒤의 값으로 채운다.
df.reindex(['a','b','c','d'],method='bfill')
df.reindex(['a','b','c','d'],method='backfill')

s = Series(['SQL','R','PYTHON'],index=[0,2,4])
s
s.reindex(range(6))
s.reindex(range(6),fill_value='ML')
s.reindex(range(6),method='ffill')
s.reindex(range(6),method='pad')
s.reindex(range(6),method='bfill')
s.reindex(range(6),method='backfill')

del s[0] # 요소 삭제(행)(즉시수행)
s.drop(4) # 인덱스 이름을 기준으로 삭제(미리보기)
s

df = DataFrame(np.arange(9).reshape(3,3),
          index=['a','c','d'],
          columns=['x','y','z'])
# 행삭제
df.drop('a') # axis=0(기본값,행삭제)(미리보기)
df_new = df.drop('a',axis=0)

# 열삭제
# del df.x 열삭제 할 수 없다. 오류
del df['x']
df.drop('x',axis=1) # axis=1(열기준) 열삭제

df.drop(['a','d'],axis=0)
df.drop(['x','y'],axis=1)

df = DataFrame(np.arange(16).reshape(4,4),
               index=['w','x','y','z'],
               columns=['one','two','three','four'])
df.one
df['one']
df[['one','four']]
df[:]
df[2:]
df[0:2]
df.iloc[0] # 인덱스 위치 기반 추출
df.loc['w'] # 인덱스 이름 기반 추출

df.loc['w','one'] # df.loc[인덱스이름, 컬럼이름]
df.loc['w',['one','four']]

df.iloc[0,0] #df.iloc[인덱스위치,컬럼위치]
df.iloc[0,[0,3]]
df.iloc[0,0:3]

df.iloc[-1]
df.iloc[:,0:2]
df.iloc[:,-1]

df[df['one'] <5]
df['one'][df['one']<5] # 특정한 조건의 열만 추출
df[df['one'] < 5, 'one'] # 특정한 조건의 열만 추출
df.loc[df['one'] < 5, 'one'] # 특정한 조건의 열만 추출
df.iloc[df['one'] < 5, 0] # 오류발생

df[df['one'] < 5][['one','four']]# 특정한 조건의 열만 추출
df.loc[df['one'] < 5, ['one','four']] # 특정한 조건의 여러개 열을 추출

'''
select one, four
from df
where one < 5;
'''

[문제80] student 데이터 프레임을 생성하세요.
      영어 수학 국어
홍길동  60  80  70
박찬호  50  70  85
손흥민  90  80  95

student = DataFrame({'영어':[60,50,90],
                     '수학':[80,70,80],
                     '국어':[70,85,95]},
                    index=['홍길동','박찬호','손흥민'])

student = DataFrame([[60,80,70],[50,70,85],[90,80,95]],
                    index=['홍길동','박찬호','손흥민'],
                    columns=['영어','수학','국어'])

# 인덱스이름, 컬럼이름
student.loc['홍길동','영어'] 
student.at['홍길동','영어']

# 인덱스위치, 컬럼위치
student.iloc[0,0]
student.iat[0,0]

# 새로운 행을 추가
student.loc['제임스','영어'] = 100
student.at['제임스','수학'] = 70
student.iloc[3,2] = 80
student.info()

# 데이터프레임의 모든 컬럼의 타입을 동일하게 수정
student.astype('int32')
student.astype('int64')
student = student.astype('int') # int32
student.info()

# 특정한 열의 데이터 타입 수정
student['영어'] = student['영어'].astype('int64')
student.info()

# 새로운 컬럼을 추가
student['과학'] = [50,70,80,60]
student
student['한국사'] = 0
student['미술사'] = np.nan # 다른 열의 타입에 영향을 주지 않음
student.info()

# 특정한 필드값을 수정하는 방법
student.loc['홍길동','미술사'] = 100
student.at['박찬호','미술사'] = 90
student.iloc[2,5] = 90
student.iat[3,5] = 100
student

# 열 삭제
del student['미술사']
student = student.drop('한국사',axis=1)

# 행 삭제
student = student.drop('제임스',axis=0)
student

# 특정한 인덱스 이름 수정
student = student.rename(index={'홍길동':'제임스'})
student

# 특정한 컬럼 이름 수정
student = student.rename(columns={'수학':'산수'})
student

# 인덱스를 컬럼으로 이동해야 할 때
student.index
student = student.reset_index()
student = student.rename(columns = {'index':'이름'})
student

# 컬럼을 인덱스로 이동해야 할 때
student = student.set_index('이름')
student.index
student.index.name = None
student

import csv
'''
select * 
from employees
where employee_id = 100;
'''
with open('c:/data/employees.csv','r') as file:
    emp_csv = csv.reader(file)
    next(emp_csv)
    for i in emp_csv:
        if i[0] == '100':
            print(i)

emp = pd.read_csv("c:/data/employees.csv")
emp.info()
emp.shape # 행과 열 길이
emp.head()
emp.head(10)
emp.tail()
emp.tail(10)

pd.options.display.max_columns # 출력할 수 있는 컬럼의 수 정보 확인
pd.get_option("display.max_columns") # 출력할 수 있는 컬럼의 수 정보 확인
pd.set_option("display.max_columns",11) # 출력할 수 있는 컬럼의 수 정보 확인
pd.reset_option("display.max_columns") # 출력할 수 있는 컬럼의 수를 기본값으로 설정

pd.options.display.max_rows # 출력할 수 있는 행의 수 정보 확인
pd.get_option("display.max_rows") # 출력할 수 있는 행의 수 정보 확인
pd.set_option("display.max_rows",1000) # 출력할 수 있는 행의 수 정보 확인
pd.reset_option("display.max_rows") # 출력할 수 있는 행의 수를 기본값으로 설정

emp.head()
emp

emp[emp['EMPLOYEE_ID'] ==100]
emp.loc[emp['EMPLOYEE_ID'] ==100,] # 행의 조건, 열
emp.loc[emp['EMPLOYEE_ID'] ==100,'LAST_NAME'] 
emp.at[emp['EMPLOYEE_ID'] ==100,'LAST_NAME'] 
emp.loc[emp['EMPLOYEE_ID'] ==100,['LAST_NAME','SALARY']] 
emp[emp['EMPLOYEE_ID'] ==100][['LAST_NAME','SALARY']]
emp[['LAST_NAME','SALARY']][emp['EMPLOYEE_ID']==100]

[문제81] JOB_ID가 ST_CLERK인 사원의 LAST_NAME, SALARY를 출력해주세요.
'''
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK'
'''
emp.loc[emp['JOB_ID']=='ST_CLERK',['LAST_NAME','SALARY']]

[문제82] SALARY가 10000이상인 사원들의 LAST_NAME,SALAYR,HIRE_DATE를 출력해주세요.
'''
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY >= 10000
'''
emp.loc[emp['SALARY']>= 10000,['LAST_NAME','SALARY','HIRE_DATE']]


정렬
obj = Series([2,7,3,8],index=['d','a','c','b'])
obj.reindex(['a','b','c','d'])
obj.sort_index() # 인덱스를 기준으로 오름차순정렬
obj.sort_index(ascending=True) 
obj.sort_index(ascending=False) # 인덱스를 기준으로 내림차순정렬

obj.sort_values() # 값을 기준으로 오름차순정렬
obj.sort_values(ascending=True) # 기본값 오름차순
obj.sort_values(ascending=False) # 값을 기준으로 내림차순정렬

df = DataFrame(np.arange(8).reshape(2,4),
          index=['two','one'],
          columns = ['d','a','c','b'])
df.reindex(['one','two'])
df.sort_index() # 인덱스를 기준으로 오름차순정렬
df.sort_index(ascending=True) #인덱스를 기준으로 오름차순정렬
df.sort_index(ascending=False) #인덱스를 기준으로 내림차순정렬
df.sort_index(axis=0,ascending=True) # 인덱스를 기준으로 오름차순정렬(axis=0,행기준, 기본값)

df.sort_index(axis=1,ascending=True) # 열이름을 기준으로 오름차순정렬(axis=1,열기준)
df.sort_index(axis=1,ascending=False) # 열이름을 기준으로 내림차순정렬(axis=1,열기준)

df.sort_values(by='a',ascending=False,axis=0) # 특정한 열의 값을 기준으로 내림차순 정렬
df.sort_values(by='one',ascending=False,axis=1) # 특정한 행(인덱스)을 기준으로 내림차순 정렬

[문제83] salary 10000 이상인 사원들의 last_name, salary, department_id 를 출력하세요. department_id를 기준으로 오름차순 정렬하세요
'''
select last_name, salary, department_id
from emp
where salary >= 10000
order by department_id
'''
test = emp.loc[emp['SALARY']>= 10000,['LAST_NAME','SALARY','DEPARTMENT_ID']].sort_values(by='DEPARTMENT_ID')
result = test.sort_values(by='DEPARTMENT_ID',ascending=True, axis=0)
result.reset_index() # 인덱스 재설정, 기존인덱스는 열로 추가
result = result.reset_index(drop=True) # 인덱스를 재설정하되 기존 인덱스를 제거하는 방법
result

'''
select last_name, salary, department_id
from emp
where salary >= 10000
order by department_id asc, salary asc;
'''
test = emp.loc[emp['SALARY']>= 10000,['LAST_NAME','SALARY','DEPARTMENT_ID']].sort_values(by='DEPARTMENT_ID')
test.sort_values(by=['DEPARTMENT_ID','SALARY'],ascending=True, axis=0)

'''
select last_name, salary, department_id
from emp
where salary >= 10000
order by department_id asc, salary desc;
'''
test = emp.loc[emp['SALARY']>= 10000,['LAST_NAME','SALARY','DEPARTMENT_ID']].sort_values(by='DEPARTMENT_ID')
test.sort_values(by=['DEPARTMENT_ID','SALARY'],ascending=[True,False], axis=0)

True or False
True | False

True and True
True & True

# in 연산자의 의미 == or ==
emp[(emp['EMPLOYEE_ID'] == 100) | (emp['EMPLOYEE_ID'] == 101)]
emp[emp['EMPLOYEE_ID'].isin([100,101])]

# not in 연산자의 의미 != and !=
# ~  : not 의미한다.
emp[(emp['EMPLOYEE_ID'] != 100) & (emp['EMPLOYEE_ID'] != 101)]
emp[~emp['EMPLOYEE_ID'].isin([100,101])]