<a href="https://colab.research.google.com/github/ehdghks316/itwill_studyGroup_D/blob/main/3_17%ED%8C%8C%EC%9D%B4%EC%8D%AC(rank%2Cpandas%EB%A1%9C_%ED%8C%8C%EC%9D%BC%EC%9D%BD%EA%B3%A0%EC%93%B0%EA%B8%B0_%EB%82%A0%EC%A7%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
[문제116] 부서이름,직업별 급여의 총액을 구하세요.
from pandas import Series,DataFrame
import pandas as pd
emp = pd.read_csv('c:/data/employees.csv')
dept = pd.read_csv('c:/data/departments.csv')

x = pd.merge(emp,dept,on='DEPARTMENT_ID')[['DEPARTMENT_NAME','JOB_ID','SALARY']]
x.groupby(['DEPARTMENT_NAME','JOB_ID'])['SALARY'].sum()

#강사님
x = emp.groupby(['DEPARTMENT_ID','JOB_ID'])['SALARY'].sum()
x.info()
x.index

df = x.reset_index() # inplace=True를 바로 적용할 수가 없다.
df
pd.merge(df,dept,on='DEPARTMENT_ID')[['DEPARTMENT_NAME','JOB_ID','SALARY']]

# NON EQUI JOIN
select e.employee_id, e.salary, j.grade_level
from emp e, job_grades j
where e.salary between j.lowest_sal and j.hightest_sal

select e.employee_id, e.salary, j.grade_level
from emp e join job_grades j
on e.salary between j.lowest_sal and j.hightest_sal

[문제117] 아래화면과 같이 출력해주세요.

      이름     급여 급여등급
0       King  24000    E
1    Kochhar  17000    E
2    De Haan  17000    E
3     Hunold   9000    C
4      Ernst   6000    C
..       ...    ...  ...

job = pd.read_csv('c:/data/job_grades.csv')
job

e = emp[['LAST_NAME','SALARY']]
e['급여등급'] = '' # 새로운 컬럼추가
for i in range(0,107,1):
    for j in range(0,6,1):
        if (job.LOWEST_SAL[j] <= e.SALARY[i]) & (e.SALARY[i] <= job.HIGHEST_SAL[j]):
            e.급여등급[i] = job.GRADE_LEVEL[j]
e.columns = ['이름','급여','급여등급']
e

# 강사님
for i in emp['SALARY']:
    print(job.loc[(i>= job.LOWEST_SAL) & (i <= job.HIGHEST_SAL),'GRADE_LEVEL'])

grade = [list(job.loc[(i>= job.LOWEST_SAL) & (i <= job.HIGHEST_SAL),'GRADE_LEVEL']) for i in emp.SALARY]    
[['A'],['E']...] -> ['A','E'] # 이렇게 바꿔줘야함
grade[0] # ['E'] 이런 식으로나옴
grade[0][0] # 'E' 이렇게 나옴
grade[1][0]

grade = [j for i in grade for j in i] # 대괄호 안에 대괄호를 풀기 
grade[0]
grade[100]

DataFrame({'이름':emp.LAST_NAME,
           '급여':emp.SALARY,
           '급여등급':grade})
# 강사님2
job
job.loc[(24000>= job.LOWEST_SAL) & (24000 <= job.HIGHEST_SAL),'GRADE_LEVEL'][4]
job.loc[(2000>= job.LOWEST_SAL) & (2000 <= job.HIGHEST_SAL),'GRADE_LEVEL'][0]

job.loc[(24000>= job.LOWEST_SAL) & (24000 <= job.HIGHEST_SAL),'GRADE_LEVEL'].reset_index(drop=True)[0] # 인덱스 0번 고정하여 문자만 추출
job.loc[(2000>= job.LOWEST_SAL) & (2000 <= job.HIGHEST_SAL),'GRADE_LEVEL'].reset_index(drop=True)[0]

grade = emp.SALARY.apply(lambda arg : job.loc[(arg>= job.LOWEST_SAL) & (arg <= job.HIGHEST_SAL),'GRADE_LEVEL'].reset_index(drop=True)[0])

DataFrame({'이름':emp.LAST_NAME,
           '급여':emp.SALARY,
           '급여등급':grade})


[문제118] 소속 사원이 있는 부서정보를 출력해주세요.
dept[dept['DEPARTMENT_ID'].isin(emp['DEPARTMENT_ID'].unique())]

[문제119] 소속 사원이 없는 부서정보를 출력해주세요.
dept[~dept['DEPARTMENT_ID'].isin(emp['DEPARTMENT_ID'].unique())]

pd.merge(emp,dept,left_on='DEPARTMENT_ID',right_on='DEPARTMENT_ID',how='inner')
pd.merge(emp,dept,left_on='DEPARTMENT_ID',right_on='DEPARTMENT_ID',how='outer')
pd.merge(emp,dept,left_on='DEPARTMENT_ID',right_on='DEPARTMENT_ID',how='left')
pd.merge(emp,dept,left_on='DEPARTMENT_ID',right_on='DEPARTMENT_ID',how='right')

new = pd.merge(emp,dept,left_on='DEPARTMENT_ID',right_on='DEPARTMENT_ID',how='right')
new[new['EMPLOYEE_ID'].isnull()][['DEPARTMENT_ID','DEPARTMENT_NAME']]

new = pd.merge(emp,dept,left_on='DEPARTMENT_ID',right_on='DEPARTMENT_ID',how='outer',indicator=True) # indicator=True merge하게되면 outer조인했을 때  어느쪽에만 있는지 표시
new[new['_merge'] == 'both']
new[new['_merge'] == 'left_only']
new[new['_merge'] == 'right_only'][['DEPARTMENT_ID','DEPARTMENT_NAME']] # 소속사원이 없는 부서정보


★ rank 
obj = Series([88,80,88,12,40,50,88,28,17,5,99])
obj.sort_values()
obj.sort_values(ascending=False)

# 오름차순순위
obj.rank()

# 내림차순순위
obj.rank(ascending=False)
DataFrame({'순위':obj.rank(ascending=False,method='average').astype(int),
           '점수':obj}) # 80점이 3명일 때 method='average' 옵션은 3명의 순위 가운데 (2,3,4) # 기본값

DataFrame({'순위':obj.rank(ascending=False,method='min').astype(int),
           '점수':obj}) # 80점이 3명일 때 method='min' 옵션은 3명의 순위 최소값

DataFrame({'순위':obj.rank(ascending=False,method='max').astype(int),
           '점수':obj}) # 80점이 3명일 때 method='max' 옵션은 3명의 순위 최대값

DataFrame({'순위':obj.rank(ascending=False,method='first').astype(int),
           '점수':obj}) # 80점이 3명일 때 method='first' 옵션은 3명이 같은 점수일 때 먼저나온 값들의 순위가 더 높게

df = DataFrame({'순위':obj.rank(ascending=False,method='dense').astype(int),
           '점수':obj}) # 80점이 3명일 때 method='dense' 옵션은  연이은 순위(순위의 갭이 없음)
df.sort_values(by='순위')

obj = Series([70,60,80,None,90])
obj.sort_values()
obj.sort_values(ascending=True,na_position='last')
obj.sort_values(ascending=False)
obj.sort_values(ascending=False,na_position='last')
obj.sort_values(ascending=False,na_position='first')

obj.rank()
obj.rank(ascending=False,na_option='keep') # na_option='keep' NaN무시(기본값)
obj.rank(ascending=False,na_option='top') # na_option='top' NaN 1등
obj.rank(ascending=False,na_option='bottom') # na_option='bottom' NaN 꼴등

df = DataFrame({'영어':[60,80,70],'수학':[50,60,86]},
               index=['이문세','윤건','나얼'])
df.rank()
df.rank(ascending=True,axis=0) # 열의 오름차순
df.rank(ascending=True,axis=1) # 행의 오름차순

df.rank(ascending=False,axis=0) 
df.rank(ascending=False,axis=1) 

[문제120] 급여를 많이 받는 순으로 10위 까지를 구하세요. 	rank, employee_id, last_name, salary를 출력하세요.
x = emp[emp['SALARY'].rank(ascending=False,method='dense') <= 10]
x[['EMPLOYEE_ID','LAST_NAME','SALARY']]
df = DataFrame({'EMPLOYEE_ID':x.EMPLOYEE_ID,
           'LAST_NAME':x.LAST_NAME,
           'SALARY':x.SALARY,
           'RANK':x.SALARY.rank(ascending=False,method='dense')})

df = df.reset_index(drop=True)

# 강사님
emp['rank'] = emp['SALARY'].rank(ascending=False,method='dense').astype(int)
emp.loc[emp['rank'] <= 10, ['rank','EMPLOYEE_ID','LAST_NAME','SALARY']].sort_values(by='rank')

emp.drop('rank',axis=1)
del emp['rank']
emp


# 파일로 만들기
emp.iloc[0:51][['EMPLOYEE_ID','LAST_NAME','SALARY']].to_csv('c:/data/emp_1.csv',index=False) # index를 제외시키고 파일로 만들기
emp.iloc[51:][['EMPLOYEE_ID','LAST_NAME','SALARY']].to_csv('c:/data/emp_2.csv',index=False) 

df = pd.read_csv('c:/data/emp_1.csv',skiprows=[0], header=None) # skiprows=행 컬럼이름 제거, header=None 컬럼이름이 없을때 컬럼이름 컬럼개수만큼 넣어줌
df.info()
df

emp1 = pd.read_csv('c:/data/emp_1.csv',skiprows=[0], header=None,names=['empid','name','sal']) # names는 컬럼이름 직접설정
emp1.head()

emp1 = pd.read_csv('c:/data/emp_1.csv',names=['empid','name','sal']) # 컬럼이름이 존재한 상태면 본 컬럼이름이 행으로 들어감 주의
emp1.info()
emp1.head()

emp2 = pd.read_csv('c:/data/emp_2.csv',skiprows=[0], header=None,names=['empid','name','sal']) # 컬럼이름이 존재한 상태면 본 컬럼이름이 행으로 들어감 주의
emp2.info()
emp2.head()

df = emp1.append(emp2,ignore_index=True)
df.info()

emp_1.csv ~ emp_100.csv

df = DataFrame()
df

for i in range(1,3):
    file = 'c:/data/emp_{}.csv'.format(i)
    temp = pd.read_csv(file,skiprows=[0], header=None,names=['empid','name','sal']) 
    df = df.append(temp,ignore_index=True)
df

# 파일을 한꺼번에 가져오는 함수
import glob
file = 'c:/data1/*'
file_lst = glob.glob(file)

df = DataFrame()
df

for f in file_lst:
    temp = pd.read_csv(f,skiprows=[0], header=None,names=['empid','name','sal']) 
    df = df.append(temp,ignore_index=True)
df

[문제121] yob2016.txt 데이터를 이용해서 아기 이름 순위 10위까지 구하세요.
# 파일에 컬럼이름이 없기때문에 이름을 지정해줘야함
# name, gender, cnt
yob = pd.read_csv('c:/data/yob2016.txt',header=None,names=['name','gender','cnt'])
yob['rank'] = yob['cnt'].rank(ascending=False,method='dense').astype('int')
yob[yob['rank'] <= 10].sort_values('rank').reset_index(drop=True)

[문제122] yob2016.txt 데이터를 이용해서  성별 아기 이름 순위 5위까지 구하세요.

yob['gender_rank'] = yob['cnt'].groupby(yob.gender).rank(ascending=False,method='dense').astype('int')
yob[yob['gender_rank']<= 5]

[문제123] yob2010.txt ~ yob2016.txt  년도별 출생수를 출력해주세요.
file = 'c:/data1/yob*'
file_lst = glob.glob(file)

df = DataFrame()
x = 2010
for i in file_lst:
    temp = pd.read_csv(i,names=['name','gender','birth','year'])
    temp['year'] = x
    df = df.append(temp)
    x += 1
df
df.birth.groupby(df.year).sum()

# 강사님
file_lst = glob.glob('c:/data1/yob*.txt')
file_lst
years=[]
y = 2010
for i in file_lst:
    df = pd.read_csv(i,names=['name','gender','birth'])
    years.append([y,df['birth'].sum()])
    y += 1
years    

for i,j in years:
    print(i,j)

with open('c:/data/years.txt','w') as file:
    file.write('년도,출생수\n')
    for i,j in years:
        data = '%s,%s\n'%(i,j)
        file.write(data)

DataFrame(years,columns=['년도','출생수']).to_csv('c:/data/years.csv',index=False)
pd.read_csv('c:/data/years.csv')    

[문제124] yob2010.txt ~ yob2016.txt  년도별 성별 출생 현황을 year_gender_total.csv 파일로 생성해주세요.
file = 'c:/data1/yob*'
file_lst = glob.glob(file)

df = DataFrame()
x = 2010
for i in file_lst:
    temp = pd.read_csv(i,names=['name','gender','birth','year'])
    temp['year'] = x
    df = df.append(temp)
    x += 1
df
df.groupby(['year','gender'])[['birth']].sum().to_csv('c:/data/year_gender_total.csv') # 파일 생성
pd.read_csv('c:/data/year_gender_total.csv') # 파일 읽기

# 강사님
file_lst = glob.glob('c:/data1/yob*.txt')
file_lst
years= DataFrame(columns=['년도','여자','남자'])
y = 2010
for i in file_lst:
    df = pd.read_csv(i,names=['name','gender','birth'])
    x = df['birth'].groupby(df.gender).sum()
    years = years.append({'년도' : y, '여자' : x.loc['F'], '남자' : x.loc['M']},ignore_index=True)
    y += 1

years.to_csv("c:/data/year_gender_total2.csv",index=False)

#####################################################

★ pandas 날짜
import datetime
datetime.datetime.now()

import pandas as pd
pd.datetime.now()

# 현재 날짜, 시간 정보를 출력하는 함수
pd.Timestamp.now()
pd.Timestamp.today()

pd.Timestamp(year=2022, month=3, day=17, hour=16, minute=43, second=30,microsecond=1,tz='Asia/Seoul')

# char -> timestamp 형변환 함수
pd.to_datetime('2022-3-17')
pd.to_datetime('2022/3/17')
pd.to_datetime('2022.3.17')
pd.to_datetime('2022317',format='%Y%m%d')
pd.to_datetime('2022317164630',format='%Y%m%d%H%M%S')

pd.Timestamp.now().year
pd.Timestamp.now().month
pd.Timestamp.now().day
pd.Timestamp.now().hour
pd.Timestamp.now().minute
pd.Timestamp.now().second
pd.Timestamp.now().microsecond
pd.Timestamp.now().dayofweek # 0~6 월~일
pd.Timestamp.now().day_name() # 영어 요일
pd.Timestamp.now().quarter

#pd.to_datetime('2021-12-16') + pd.Timestamp.now() # 날짜 + 날짜는 안됨
pd.to_datetime('2021-12-16') - pd.Timestamp.now()
pd.Timestamp.now() - pd.to_datetime('2021-12-16')
(pd.to_datetime('2022-5-20') - pd.Timestamp.now()).days # 일수만 출력
pd.Timestamp.now() + pd.Timedelta('64 days') # 날짜 + 일수 = 날짜
pd.Timestamp.now() - pd.Timedelta('91 days')
pd.Timestamp.now() + pd.Timedelta('1 hours')
pd.Timestamp.now() + pd.Timedelta('60 minutes')
pd.Timestamp.now() + pd.Timedelta('60 min')
pd.Timestamp.now() + pd.Timedelta('3600 second')
pd.Timestamp.now() + pd.Timedelta('3600 sec')
pd.Timestamp.now() + pd.Timedelta('365 days 10 hours 3600 sec')
pd.Timestamp.now() + pd.Timedelta('365 day 10 hour 3600 sec')
pd.Timestamp.now() + pd.Timedelta('10 day 1:30:00')

pd.Timestamp.now() + pd.Timedelta('365 days 1:30:0') # 년을 더하려면 일수로 환산해서 계산해야함
pd.Timestamp.now() + pd.DateOffset(years=10,months=1) # 년수 개월수를 더한다.

# 날짜 시간 수정
pd.Timestamp.now() + pd.DateOffset(year=2021,month=1,day=1,hour=0,minute=0,second=0,microsecond=0)